# Generated by Django 6.0 on 2025-12-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_adminregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminregistration_name', models.CharField(max_length=30)),
                ('adminregistration_email', models.CharField(max_length=30)),
                ('adminregistration_password', models.CharField(max_length=30)),
            ],
        ),
    ]
