# Generated by Django 6.0.2 on 2026-02-14 11:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIEMRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('rule_type', models.CharField(choices=[('FAILED_LOGIN_BURST', 'Failed Login Burst')], max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('threshold', models.PositiveIntegerField(default=5)),
                ('window_seconds', models.PositiveIntegerField(default=60)),
                ('severity_default', models.IntegerField(default=7)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_ATTEMPT', 'Login Attempt'), ('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILURE', 'Login Failure')], max_length=40)),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.CharField(blank=True, default='', max_length=255)),
                ('src_ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('outcome', models.CharField(blank=True, default='', max_length=20)),
                ('severity', models.IntegerField(default=1)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['ts'], name='Guest_secur_ts_1ec7cd_idx'), models.Index(fields=['event_type', 'ts'], name='Guest_secur_event_t_aadae0_idx'), models.Index(fields=['actor', 'ts'], name='Guest_secur_actor_2ab39f_idx'), models.Index(fields=['src_ip', 'ts'], name='Guest_secur_src_ip_f5e521_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACK', 'Acknowledged'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('actor', models.CharField(blank=True, default='', max_length=255)),
                ('src_ip', models.CharField(blank=True, default='', max_length=64)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('ack_note', models.TextField(blank=True, default='')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.securityevent')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.siemrule')),
            ],
        ),
    ]
